cameras:
  - name: front_left
    device: /dev/video0
    width: 1280
    height: 720
    fps: 30 # NOTE: This is not working; but we set the frame sync setting below
    subsample_factor: 1
    settings:
      - name: vertical_flip
        value: 1
      - name: white_balance_automatic
        value: 0
      - name: frame_sync
        value: 1 # Frame Sync 30 Hz
        id: 0x009a092a
    format: UYVY
    req_buffer_count: 4
    transforms:
      - name: UYVY2RGB
  - name: front_right
    device: /dev/video1
    width: 1280
    height: 720
    fps: 30
    subsample_factor: 1
    settings:
      - name: vertical_flip
        value: 1
      - name: white_balance_automatic
        value: 0
      - name: frame_sync
        value: 1
        id: 0x009a092a
    format: UYVY
    req_buffer_count: 4
    transforms:
      - name: UYVY2RGB
  - name: left
    device: /dev/video2
    width: 1280
    height: 720
    fps: 30
    subsample_factor: 1
    settings:
      - name: vertical_flip
        value: 1
      - name: white_balance_automatic
        value: 0
      - name: frame_sync
        value: 1
        id: 0x009a092a
    format: UYVY
    req_buffer_count: 1
    transforms:
      - name: UYVY2RGB
  - name: right
    device: /dev/video3
    width: 1280
    height: 720
    fps: 30
    subsample_factor: 1
    settings:
      - name: vertical_flip
        value: 1
      - name: white_balance_automatic
        value: 0
      - name: frame_sync
        value: 1
        id: 0x009a092a
    format: UYVY
    req_buffer_count: 1
    transforms:
      - name: UYVY2RGB
imus:
  - name: accelerometer
    device: "iio:device0"
    sampling_frequency: 1000 # Hz
    buffer_samples: 128
    cyclic_buffer: true
    channels:
      - "in_accel_x"
      - "in_accel_y"
      - "in_accel_z"
  - name: gyroscope
    device: "iio:device1"
    sampling_frequency: 1000 # Hz
    buffer_samples: 128
    cyclic_buffer: true
    channels:
      - "in_anglvel_x"
      - "in_anglvel_y"
      - "in_anglvel_z"
shared_memory:
  - name: front_left
    size_per_frame: 2764800 # 1280*720*3 bytes
    num_frames: 300 # 10 seconds at 30 fps
  - name: front_right
    size_per_frame: 2764800 # 1280*720*3 bytes
    num_frames: 300 # 10 seconds at 30 fps
  - name: left
    size_per_frame: 2764800 # 1280*720*3 bytes
    num_frames: 300 # 10 seconds at 30 fps
  - name: right
    size_per_frame: 2764800 # 1280*720*3 bytes
    num_frames: 300 # 10 seconds at 30 fps
